micronaut:
  application:
    name: onboarding
camunda:
  admin-user:
    id: admin
    password: admin
    firstname: Tobias
    lastname: Schäfer
  generic-properties:
    properties:
      initialize-telemetry: true
  webapps:
    enabled: true
  rest:
    enabled: true
  filter:
    create: "All tasks"
